"""add filing download metadata

Revision ID: 44f256e2accf
Revises: cec869d42e85
Create Date: 2026-10-08 23:52:18.348148

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44f256e2accf"
down_revision: str | Sequence[str] | None = "cec869d42e85"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("filings", sa.Column("raw_document_path", sa.String(length=1000), nullable=True))
    op.add_column("filings", sa.Column("content_sha256", sa.String(length=64), nullable=True))
    op.add_column("filings", sa.Column("downloaded_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("filings", "downloaded_at")
    op.drop_column("filings", "content_sha256")
    op.drop_column("filings", "raw_document_path")
    # ### end Alembic commands ###
